# =============================================================================
# Copyright (c) 2026 KritvaOS
# SPDX-License-Identifier: Apache-2.0
#
# File        : fsm_structural.py
# Description : Fsm Structural implementation
#
# Component   : Kritva Forge
# Module      : structural
# Layer       : Structural Analysis
#
# Author      : Kritva Forge Team
# Created     : 02-10-2026
# =============================================================================
# ---------------------------------------------------------------
# ├── fsm_structural.py      # Main orchestrator
# ├── fsm_graph.py           # Structural graph construction
# ├── fsm_symbol_db.py       # Symbol/state database
# ├── fsm_scoring.py         # FSM scoring heuristics
# └── fsm_transition.py      # (Future)
# ---------------------------------------------------------------
# 
# fsm_structural.py
#         │
#         ├──────────────┬──────────────┬──────────────┐
#         ▼              ▼              ▼              ▼
# fsm_graph.py   fsm_symbol_db.py   fsm_scoring.py   fsm_transition.py
#         │              │              │              │
#         └──────────────┴──────────────┴──────────────┘
# ------------------------------------------------------------------


import re
from collections import defaultdict
from scripts.parser.ast_utils import extract_identifiers,get_primary_role

from scripts.fsm.fsm_graph import ( build_assignment_graph, build_case_usage_db,)

from scripts.fsm.fsm_symbol_db import ( build_symbol_db,)

from scripts.fsm.fsm_selector import (
    select_best_state_register,
    select_best_next_state,
    compute_confidence,
    detect_fsm_style,
)

from scripts.fsm.fsm_scoring import ( score_state_registers, score_next_state_signals,)

from scripts.fsm.fsm_models import StructuralFSM


# ------------------------------------------------------------
# 
# ------------------------------------------------------------

def validate_state_candidates(module_info):

    structural = module_info["structural"]

    validated = []

    for cand in structural["state_candidates"]:

        validated.append(

            validate_state_candidate(

                cand,

                module_info

            )
        )

    structural["validated_state_candidates"] = validated

# --------------------------------------------------------
# 
# --------------------------------------------------------

def validate_next_state_candidates(module_info,
                                   state_candidate=None):

    structural = module_info.setdefault("structural", {})

    validated = []

    for cand in structural.get("next_state_candidates", []):

        validated.append(

            validate_next_state_candidate(

                cand,

                module_info,

                state_candidate

            )

        )

    structural["validated_next_candidates"] = validated

    return validated

# -----------------------------------------------------
#
# -----------------------------------------------------

def validate_next_state_candidate(candidate,
                                  module_info,
                                  state_candidate=None):
    """
    Validate structural evidence for a next-state signal.

    Parameters
    ----------
    candidate : dict
        Candidate generated by generate_next_state_candidates()

    module_info : dict

    state_candidate : dict | None
        Best validated state register candidate (optional)

    Returns
    -------
    Updated candidate
    """

    structural = module_info.get("structural", {})

    signal = candidate["signal"]

    evidence = set(candidate.get("evidence", []))

    features = candidate.get("features", {})

    required = {

        "always_comb": False,

        "case": False,

        "drives_state": False,

        "width_match": False
    }

    bonus = []

    penalty = []

    #
    # ---------------------------------------------------
    # Required Evidence
    # ---------------------------------------------------
    #

    if "always_comb" in evidence:
        required["always_comb"] = True

    if "case" in evidence:
        required["case"] = True

    if "drives_state" in evidence:
        required["drives_state"] = True

    #
    # ---------------------------------------------------
    # Width check
    # ---------------------------------------------------
    #

    if state_candidate:

        state_width = state_candidate.get("width", 1)

        next_width = candidate.get("width", 1)

        if state_width == next_width:

            required["width_match"] = True

    #
    # ---------------------------------------------------
    # Bonus
    # ---------------------------------------------------
    #

    if "next_name" in evidence:
        bonus.append("next_name")

    if "small_width" in evidence:
        bonus.append("small_width")

    deps = features.get("dependencies", [])

    if deps:

        bonus.append("dependency")

    #
    # ---------------------------------------------------
    # Penalties
    # ---------------------------------------------------
    #

    lname = signal.lower()

    BAD_SUFFIX = (

        "_cnt",
        "_counter",
        "_addr",
        "_data",
        "_mask",
        "_ptr",
        "_crc",
        "_sum",
        "_size",
        "_index"

    )

    if lname.endswith(BAD_SUFFIX):

        penalty.append("datapath_name")

    width = candidate.get("width", 1)

    if width > 16:

        penalty.append("large_width")

    #
    # Arithmetic expression usually indicates datapath
    #

    if any(

        "+" in str(d)
        or
        "-" in str(d)
        or
        "*" in str(d)

        for d in deps

    ):

        penalty.append("arithmetic")

    #
    # ---------------------------------------------------
    # Validation
    # ---------------------------------------------------
    #

    required_count = sum(required.values())

    if required_count >= 3:

        valid = True

        confidence = "high"

    elif required_count == 2 and len(bonus) >= 2:

        valid = True

        confidence = "medium"

    elif required_count == 2:

        valid = True

        confidence = "low"

    else:

        valid = False

        confidence = "reject"

    #
    # Too many penalties
    #

    if len(penalty) >= 2:

        valid = False

        confidence = "reject"

    #
    # Save results
    #

    candidate["valid"] = valid

    candidate["confidence"] = confidence

    candidate["required"] = required

    candidate["bonus"] = bonus

    candidate["penalty"] = penalty

    return candidate

# --------------------------------------
#
# --------------------------------------

def generate_next_state_candidates(module_info,best_state_reg):
    """
    Generate next-state candidates.

    No scoring.
    """

    structural = module_info.setdefault("structural", {})

    roles = structural.get("always_roles", {})
    assignment_graph = structural.get("assignment_graph", {})
    case_usage = structural.get("case_usage", {})

    signals = module_info.get("signals", [])

    candidates = []

    for sig in signals:

        if sig.get("direction"):
            continue

        name = sig["name"]


        role = get_primary_role( roles, name)
        
        if role is None:
            continue
        
        if role["type"] != "always_comb":
            continue


        cand = {

            "signal": name,

            "role": None,

            "width": sig.get("width", 1),

            "evidence": [],

            "features": {},

            "score": 0,

            "valid": False
        }





        if role:

            cand["role"] = role["type"]

            if role["type"] == "always_comb":

                cand["evidence"].append("always_comb")

        if name in case_usage:

            cand["evidence"].append("case")

        deps = assignment_graph.get(name, [])

        if deps:

            cand["features"]["dependencies"] = deps

            #
            # drives state register
            #

            if best_state_reg in deps:
                cand["evidence"].append("drives_state")

        lname = name.lower()

        if "next" in lname:

            cand["evidence"].append("next_name")

        elif lname.endswith("_n"):

            cand["evidence"].append("next_name")

        elif lname.endswith("_ns"):

            cand["evidence"].append("next_name")

        elif lname.endswith("_next"):

            cand["evidence"].append("next_name")

        width = sig.get("width")

        if width and width <= 8:

            cand["evidence"].append("small_width")

        candidates.append(cand)

    structural["next_state_candidates"] = candidates

    return candidates

# --------------------------------------
#
# --------------------------------------
def generate_state_candidates(module_info):
    """
    Generate possible FSM state register candidates.

    No scoring is performed here.
    Only collect structural evidence.
    """

    structural = module_info.setdefault("structural", {})

    roles = structural.get("always_roles", {})
    assignment_graph = structural.get("assignment_graph", {})
    case_usage = structural.get("case_usage", {})
    state_value_db = structural.get("state_value_db", {})
    reset_assignments = structural.get("reset_assignments", {})

    candidates = []

    signals = module_info.get("signals", [])
    
    roles = structural.get("always_roles", {})
    
    for sig in signals:
    
        #
        # Ignore ports
        #
        if sig.get("direction"):
            continue
    
        name = sig["name"]

        role = get_primary_role( roles, name)
    
        #
        # Only sequential registers
        #
        if role is None:
            continue
    
        if role["type"] != "always_ff":
            continue

        name = sig["name"]

        cand = {

            "signal": name,

            "role": None,

            "width": sig.get("width", 1),

            "evidence": [],

            "features": {},

            "score": 0,

            "valid": False
        }

        #
        # -------------------------------------------------
        # Always role
        # -------------------------------------------------
        #

        if role:

            cand["role"] = role["type"]

            if role["type"] == "always_ff":

                cand["evidence"].append("always_ff")

        #
        # -------------------------------------------------
        # Appears in CASE()
        # -------------------------------------------------
        #

        if name in case_usage:

            cand["evidence"].append("case")

            cand["features"]["case_count"] = \
                case_usage[name]

        #
        # -------------------------------------------------
        # Has enum values
        # -------------------------------------------------
        #

        if name in state_value_db:

            cand["evidence"].append("enum")

            cand["features"]["states"] = \
                state_value_db[name]

        #
        # -------------------------------------------------
        # Reset assignment
        # -------------------------------------------------
        #

        if name in reset_assignments:

            cand["evidence"].append("reset")

        #
        # -------------------------------------------------
        # Assignment graph
        # -------------------------------------------------
        #

        deps = assignment_graph.get(name, [])

        if deps:

            cand["features"]["dependencies"] = deps

            #
            # feedback
            #
            if name in deps:

                cand["evidence"].append("feedback")

            #
            # next-state relation
            #
            if any(

                "_next" in d.lower()

                for d in deps

            ):

                cand["evidence"].append("next_relation")

        #
        # -------------------------------------------------
        # Width
        # -------------------------------------------------
        #

        width = sig.get("width")

        if width:

            cand["features"]["width"] = width

            if width <= 8:

                cand["evidence"].append("small_width")

        #
        # -------------------------------------------------
        # Naming hints
        # -------------------------------------------------
        #

        lname = name.lower()

        if "state" in lname:

            cand["evidence"].append("state_name")

        elif lname.endswith("_st"):

            cand["evidence"].append("state_name")

        elif lname.endswith("_fsm"):

            cand["evidence"].append("state_name")

        candidates.append(cand)

    structural["state_candidates"] = candidates

    return candidates

# --------------------------------------
#
# --------------------------------------

def validate_state_candidate(candidate, module_info):
    """
    Validate structural evidence for an FSM state register.

    This routine DOES NOT assign the final score.

    It only determines

        valid
        confidence
        bonus
        penalty
    """

    structural = module_info.get("structural", {})

    signal = candidate["signal"]

    evidence = set(candidate.get("evidence", []))

    features = candidate.get("features", {})

    required = {

        "always_ff": False,

        "case": False,

        "feedback": False,

        "reset": False,

        "enum": False
    }

    bonus = []

    penalty = []

    #
    # ------------------------------
    # Required Evidence
    # ------------------------------
    #

    if "always_ff" in evidence:
        required["always_ff"] = True

    if "case" in evidence:
        required["case"] = True

    if "feedback" in evidence:
        required["feedback"] = True

    if "reset" in evidence:
        required["reset"] = True

    if "enum" in evidence:
        required["enum"] = True

    #
    # ------------------------------
    # Bonus
    # ------------------------------
    #

    if "state_name" in evidence:
        bonus.append("state_name")

    if "small_width" in evidence:
        bonus.append("small_width")

    if "next_relation" in evidence:
        bonus.append("next_relation")

    if len(features.get("states", [])) >= 2:
        bonus.append("multi_state")

    #
    # ------------------------------
    # Penalty
    # ------------------------------
    #

    lname = signal.lower()

    BAD_SUFFIX = (

        "_cnt",

        "_counter",

        "_addr",

        "_data",

        "_mask",

        "_ptr",

        "_index",

        "_byte",

        "_crc",

        "_sum",

        "_size"
    )

    if lname.endswith(BAD_SUFFIX):

        penalty.append("datapath_name")

    width = features.get("width", 1)

    if width > 16:

        penalty.append("large_width")

    deps = features.get("dependencies", [])

    #
    # Arithmetic usually indicates counters,
    # not FSM state registers.
    #
    if any(

        "+" in str(d)

        or

        "-" in str(d)

        for d in deps

    ):

        penalty.append("arithmetic")

    #
    # ------------------------------
    # Determine validity
    # ------------------------------
    #

    required_count = sum(required.values())

    #
    # Strong FSM
    #
    if required_count >= 4:

        valid = True

        confidence = "high"

    #
    # Typical two-process FSM
    #
    elif required_count == 3:

        valid = True

        confidence = "medium"

    #
    # Weak evidence
    #
    elif required_count == 2 and len(bonus) >= 2:

        valid = True

        confidence = "low"

    else:

        valid = False

        confidence = "reject"

    #
    # Too many penalties?
    #
    if len(penalty) >= 2:

        valid = False

        confidence = "reject"

    candidate["valid"] = valid

    candidate["confidence"] = confidence

    candidate["required"] = required

    candidate["bonus"] = bonus

    candidate["penalty"] = penalty

    return candidate

# --------------------------------------
# 
# --------------------------------------
def structural_fsm_analysis(
        module_info
        ):
    """
    ===========================================================
    Structural FSM Analysis

    Builds the complete structural database used by

        • FSM Detection
        • FSM Quality
        • Transition Recovery
        • RTL Agent
        • Dataset Generation

    ===========================================================
    """

    #
    # ---------------------------------------------------------
    # Assignment / Dependency Graph
    # ---------------------------------------------------------
    #

    graph_db = build_assignment_graph( module_info)

    assignment_graph = graph_db.get( "assignment_graph", {})

    dependency_graph = graph_db.get( "dependency_graph", {})

    always_roles = graph_db.get( "always_roles", {})


    # --------------------------------------------------------
    # build_case_database()
    # --------------------------------------------------------

    case_usage = build_case_usage_db(module_info)

    # --------------------------------------------------------
    # build_state_value_db()
    # --------------------------------------------------------
    # ---------------------------------------------------------
    # Symbolic State Database
    # ---------------------------------------------------------

    state_db = build_symbol_db(module_info)

    state_value_db = state_db["state_value_db"]

    symbol_db = state_db["symbol_db"]

    # --------------------------------------------------------
    # generate_state_candidates
    # --------------------------------------------------------

    generate_state_candidates(module_info)

    # -------------------------------------------------------
    # validate_state_candidates
    # ---------------------------------------------------------
    validate_state_candidates(module_info)

    #
    # ---------------------------------------------------------
    # Candidate State Registers
    # ---------------------------------------------------------
    #

    state_scores = score_state_registers(

        module_info,

        assignment_graph,

        dependency_graph,

        always_roles,

        case_usage,

        state_value_db,

        symbol_db

    )

    #
    # ---------------------------------------------------------
    # Select Best State Register
    # ---------------------------------------------------------
    #

    best_state_reg = None

    if state_scores:

        best_state_reg = select_best_state_register( state_scores)

    # --------------------------------------------------------
    # generate_next_state_candidates
    # --------------------------------------------------------
    generate_next_state_candidates( module_info, best_state_reg)

    # ---------------------------------------------------------
    # validate_next_state_candidates
    # ---------------------------------------------------------

    validate_next_state_candidates( module_info, best_state_reg)


    #
    # ---------------------------------------------------------
    # Candidate Next-State Signals
    # ---------------------------------------------------------
    #

    next_scores = score_next_state_signals(

        module_info,

        best_state_reg,

        assignment_graph,

        dependency_graph,

        always_roles,

        case_usage,

        state_value_db,

        symbol_db

    )

    #
    # ---------------------------------------------------------
    # Select Best Next-State
    # ---------------------------------------------------------
    #

    best_next_state = None

    if next_scores:

        # ---------------------------------------------------------
        # Select Best Next-State
        # ---------------------------------------------------------
        
        best_next_state = select_best_next_state(
            next_scores
        )

    #
    # ---------------------------------------------------------
    # FSM Style
    # ---------------------------------------------------------
    #

    style = detect_fsm_style(
        always_roles,
        best_state_reg,
        best_next_state
    )

    # ---------------------------------------------------------
    # select_best_candidates
    # --------------------------------------------------------

    
    # ---------------------------------------------------------
    # detect_style
    # ---------------------------------------------------------


    #
    # ---------------------------------------------------------
    # Confidence
    # ---------------------------------------------------------
    #
    confidence = compute_confidence(
        state_scores,
        best_state_reg,
        best_next_state,
        state_value_db,
        always_roles,
        style
    )


    #
    # ---------------------------------------------------------
    # Return Structural Database
    # ---------------------------------------------------------
    #

    return StructuralFSM(
        #
        # Structural Databases
        #

        assignment_graph=assignment_graph,
    
        dependency_graph=dependency_graph,
    
        always_roles=always_roles,
    
        case_usage=case_usage,
    
        symbol_db=symbol_db,

        #
        # Candidate Scores
        #
    
        state_value_db=state_value_db,
    
        state_scores=state_scores,
    
        next_scores=next_scores,

        #
        # Selected FSM
        #
    
        best_state_reg=best_state_reg,
    
        best_next_state=best_next_state,

        #
        # Classification
        #
    
        style=style,
    
        confidence=confidence,
    )
